export const BOOT_LINES = [
  {
    id: 'init',
    prefix: '>',
    segments: [
      { text: 'initializing system... WOWEN OS v0.1 — pre-release build' },
    ],
    tone: 'dim',
    typeSpeed: 30,
    pauseAfter: 1450,
  },
  {
    id: 'break-intro',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 850,
  },
  {
    id: 'entity',
    prefix: '>',
    segments: [{ text: 'loading entity: EMMA_HAGER' }],
    tone: 'strong',
    typeSpeed: 30,
    pauseAfter: 1300,
  },
  {
    id: 'statement',
    segments: [
      { text: "EMMA_HAGER builds things that make sense in a world that doesn't." },
    ],
    tone: 'strong',
    typeSpeed: 31,
    pauseAfter: 1350,
  },
  {
    id: 'role',
    segments: [{ text: 'role: Product Lead / Systems Architect' }],
    typeSpeed: 30,
    pauseAfter: 780,
  },
  {
    id: 'status',
    segments: [
      { text: 'status: ' },
      { text: 'active', accent: true },
    ],
    typeSpeed: 28,
    pauseAfter: 1200,
  },
  {
    id: 'break-identity',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'scan',
    prefix: '>',
    segments: [{ text: 'scanning capabilities...' }],
    tone: 'dim',
    typeSpeed: 28,
    pauseAfter: 1450,
  },
  {
    id: 'scope',
    segments: [
      {
        text: 'EMMA_HAGER operates across product, systems, code, security, design & communication',
      },
    ],
    tone: 'strong',
    typeSpeed: 29,
    pauseAfter: 1650,
  },
  {
    id: 'cap-product',
    prefix: '✔',
    segments: [{ text: 'product strategy', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 950,
  },
  {
    id: 'cap-ux',
    prefix: '✔',
    segments: [{ text: 'ux/design', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 950,
  },
  {
    id: 'cap-stack',
    prefix: '✔',
    segments: [{ text: 'full-stack execution', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 950,
  },
  {
    id: 'cap-narrative',
    prefix: '✔',
    segments: [{ text: 'narrative engineering', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 1150,
  },
  {
    id: 'break-capabilities',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'cognitive-scan',
    prefix: '>',
    segments: [{ text: 'scanning cognitive profile...' }],
    tone: 'dim',
    typeSpeed: 28,
    pauseAfter: 1250,
  },
  {
    id: 'capability-signature',
    segments: [{ text: 'capability signature:' }],
    tone: 'strong',
    typeSpeed: 28,
    pauseAfter: 900,
  },
  {
    id: 'cap-gap',
    prefix: '✔',
    segments: [
      { text: 'see gaps others overlook: ' },
      { text: 'VERY HIGH', accent: true },
    ],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'cap-opportunity',
    prefix: '✔',
    segments: [
      { text: 'spot unbuilt opportunities: ' },
      { text: 'HIGH', accent: true },
    ],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'cap-cost',
    prefix: '✔',
    segments: [
      { text: 'cost leak detection: ' },
      { text: 'INSTANT', accent: true },
    ],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'cap-builds',
    prefix: '✔',
    segments: [
      { text: "builds what doesn't exist: " },
      { text: 'DEFAULT', accent: true },
    ],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'cap-cuts',
    prefix: '✔',
    segments: [
      { text: "cuts what shouldn't exist: " },
      { text: 'DEFAULT', accent: true },
    ],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 1150,
  },
  {
    id: 'break-cognitive',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'module-scan',
    prefix: '>',
    segments: [{ text: 'scanning additional modules...' }],
    tone: 'dim',
    typeSpeed: 28,
    pauseAfter: 1050,
  },
  {
    id: 'module-creative',
    prefix: '✔',
    segments: [{ text: 'multidisciplinary creative', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'module-impact',
    segments: [{ text: 'impact: creative override' }],
    tone: 'dim',
    typeSpeed: 26,
    pauseAfter: 1200,
  },
  {
    id: 'break-modules',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'signal-scan',
    prefix: '>',
    segments: [{ text: 'scanning for more signals...' }],
    tone: 'dim',
    typeSpeed: 28,
    pauseAfter: 1100,
  },
  {
    id: 'signal-composer',
    prefix: '✔',
    segments: [{ text: 'classical music composer', accent: true }],
    tone: 'accent',
    typeSpeed: 26,
    pauseAfter: 850,
  },
  {
    id: 'signal-classification',
    segments: [{ text: 'classification: non-critical / retained' }],
    tone: 'dim',
    typeSpeed: 26,
    pauseAfter: 1300,
  },
  {
    id: 'break-signals',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'process',
    prefix: '>',
    segments: [{ text: 'resolving anomaly signature', dots: true }],
    tone: 'dim',
    typeSpeed: 28,
    pauseAfter: 2200,
  },
  {
    id: 'anomaly',
    segments: [{ text: 'anomaly detected:' }],
    tone: 'strong',
    typeSpeed: 28,
    pauseAfter: 1250,
  },
  {
    id: 'thinking',
    segments: [{ text: 'thinking model: non-linear' }],
    offset: 'detail',
    typeSpeed: 28,
    pauseAfter: 950,
  },
  {
    id: 'pattern',
    segments: [
      { text: 'pattern recognition: ' },
      { text: 'HIGH', accent: true },
    ],
    offset: 'detail',
    typeSpeed: 28,
    pauseAfter: 1450,
  },
  {
    id: 'break-proceed',
    segments: [{ text: '--------------------------------' }],
    tone: 'dim',
    typeSpeed: 20,
    pauseAfter: 900,
  },
  {
    id: 'proceed',
    prefix: '>',
    segments: [{ text: 'proceed?' }],
    typeSpeed: 28,
    pauseAfter: 0,
  },
]

export const CONTACT_LINKS = [
  {
    id: 'email',
    command: 'transmit signal',
    target: 'email',
    href: 'mailto:emma@wowen.se',
    destination: 'mailto:emma@wowen.se',
    kind: 'external',
  },
  {
    id: 'github',
    command: 'inspect codebase',
    target: 'github',
    href: 'https://github.com/uchusei',
    destination: 'github.com/uchusei',
    handoffPath: '/handoff/github.html',
    kind: 'external',
  },
  {
    id: 'linkedin',
    command: 'verify identity',
    target: 'linkedin',
    href: 'https://linkedin.com/in/emmahager',
    destination: 'linkedin.com/in/emmahager',
    handoffPath: '/handoff/linkedin.html',
    kind: 'external',
  },
  {
    id: 'access',
    command: 'request access',
    target: 'enter wowen',
    kind: 'internal',
  },
]

export function buildRouteTranscript(route) {
  if (route.kind === 'internal') {
    return [
      {
        id: `${route.id}-denied`,
        segments: [{ text: 'access denied' }],
        tone: 'warning',
        typeSpeed: 24,
        pauseAfter: 850,
      },
      {
        id: `${route.id}-reason`,
        segments: [{ text: 'reason: not publicly deployed' }],
        tone: 'dim',
        typeSpeed: 24,
        pauseAfter: 850,
      },
      {
        id: `${route.id}-override`,
        segments: [{ text: 'override: contact required' }],
        tone: 'dim',
        typeSpeed: 24,
        pauseAfter: 0,
      },
    ]
  }

  return [
    {
      id: `${route.id}-opening`,
      prefix: '>',
      segments: [{ text: 'opening external route...' }],
      tone: 'dim',
      typeSpeed: 24,
      pauseAfter: 700,
    },
    {
      id: `${route.id}-destination`,
      prefix: '>',
      segments: [{ text: `destination: ${route.destination}` }],
      tone: 'strong',
      typeSpeed: 24,
      pauseAfter: 700,
    },
    {
      id: `${route.id}-handoff`,
      prefix: '>',
      segments: [{ text: 'handoff confirmed' }],
      tone: 'dim',
      typeSpeed: 24,
      pauseAfter: 350,
    },
  ]
}
